version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"
    networks:
        - default
    healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "5672" ]
        interval: 5s
        timeout: 15s
        retries: 1
  user:
    build: .
    container_name: user
    ports:
        - "9000:80"
    restart: on-failure
    depends_on:
        - "rabbitmq"
    volumes:
        - ./user:/var/www/html/nextbasket-test
    networks:
        - default
    working_dir: /var/www/html/nextbasket-test       
  notification:
      build: .
      container_name: notification
      ports:
          - "9001:80"
      restart: on-failure
      depends_on:
          - "rabbitmq"
      volumes:
          - ./notifiction:/var/www/html/nextbasket-test
      networks:
          - default
      working_dir: /var/www/html/nextbasket-test        